server:
  port: 8001
  servlet:
    context-path: /member

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf6087x4566hm2xs86o.rwlb.rds.aliyuncs.com/train_member?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_member
    password: train=12306
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com.papupupu.train.member.mapper: trace
