server:
  port: 8000
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
#            allowCredentials: true
#            maxAge: 3600
      routes:
        - id: member
          predicates:
            - Path=/member/**
          uri: http://localhost:8001