server:
  port: 8002
  servlet:
    context-path: /business

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://116.196.74.159:13306/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://116.196.74.159:13306/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: Zx20020624


    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 15 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 25 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com.papupupu.train.business.mapper: trace
